"use client"

import type React from "react"

import { useState, useEffect, useRef } from "react"
import Link from "next/link"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import HeroSection from "@/components/HeroSection"
import { YCRfsSection } from "@/components/YCRfsSection"
import { FeaturesSection } from "@/components/FeaturesSection"
import {
  Navbar,
  NavBody,
  NavItems,
  MobileNav,
  MobileNavHeader,
  MobileNavToggle,
  MobileNavMenu,
  NavbarButton,
} from "@/components/ui/resizable-navbar"
import {
  ArrowRight,
  Check,
  ShieldCheck,
  Brain,
  Users,
  Target,
  Award,
  TrendingUp,
  FileCheck,
  Sparkles,
  ChevronRight,
  BarChart3,
  Lock,
  Eye,
  GitBranch,
  FileText,
  MessageSquare,
  Briefcase,
  GraduationCap,
  Star,
  ArrowUpRight,
  CheckCircle2,
  XCircle,
  Minus,
  Rocket,
} from "lucide-react"

import {
  SiLinkedin,
  SiGithub,
  SiGoogle,
  SiSlack,
  SiNotion,
  SiFigma,
  SiIndeed,
  SiGreenhouse,
  SiSalesforce,
  SiHubspot,
  SiZendesk
} from "react-icons/si"
import { FaMicrosoft } from "react-icons/fa"

const INTEGRATIONS = [
  { name: "LinkedIn", icon: SiLinkedin },
  { name: "GitHub", icon: SiGithub },
  { name: "Google", icon: SiGoogle },
  { name: "Slack", icon: SiSlack },
  { name: "Notion", icon: SiNotion },
  { name: "Figma", icon: SiFigma },
  { name: "Microsoft", icon: FaMicrosoft },
  { name: "Indeed", icon: SiIndeed },
  { name: "Greenhouse", icon: SiGreenhouse },
  { name: "HubSpot", icon: SiHubspot },
  { name: "Zendesk", icon: SiZendesk },
  { name: "Salesforce", icon: SiSalesforce },
]

const STATS = [
  { value: "10x", label: "Faster Time from Idea to Live Product" },
  { value: "3x", label: "More Revenue Channels Activated by Agents" },
  { value: "<24h", label: "Average Time from Goal to Deployed MVP" },
  { value: "24/7", label: "Agents Working While You Sleep" },
]

const FORGE_VS_CRM = [
  { feature: "Product Building (No-Code)", forge: true, ats: false },
  { feature: "Product-Market Fit Validation", forge: true, ats: false },
  { feature: "Go-to-Market Strategy", forge: true, ats: false },
  { feature: "Outbound Sales Execution", forge: true, ats: "partial" },
  { feature: "Marketing Campaign Management", forge: true, ats: false },
  { feature: "Competitor & Market Monitoring", forge: true, ats: false },
  { feature: "Revenue & Growth Forecasting", forge: true, ats: false },
  { feature: "Requires a Full Engineering Team", forge: false, ats: true },
  { feature: "Requires Dedicated Sales Hire", forge: true, ats: true },
  { feature: "High Monthly Burn Rate", forge: true, ats: true },
]

const INTELLIGENCE_MODULES = [
  { name: "PMF Validation Engine", icon: Target, description: "Test value props before building features" },
  { name: "Live Trend Radar", icon: BarChart3, description: "Scan HackerNews/X for buying signals" },
  { name: "Revenue Forecaster", icon: TrendingUp, description: "Predictive ARR & Churn Modeling" },
  { name: "Agentic Outreach", icon: Rocket, description: "Self-optimizing email campaigns" },
  { name: "Market Blueprint", icon: Briefcase, description: "Autogenerated 30-day GTM plans" },
]

const AUTOMATION_TIERS = [
  {
    tier: "Full Autopilot",
    multiplier: "1.0x",
    description: "Agents build, launch, sell, and iterate your entire company with zero human input.",
    color: "text-zinc-300",
  },
  {
    tier: "Founder Approval Mode",
    multiplier: "0.7x",
    description: "Agents prepare everything — you approve before anything goes live.",
    color: "text-zinc-300",
  },
  { tier: "Co-Pilot Mode", multiplier: "0.4x", description: "Agents suggest what to build and who to target; you stay hands-on with execution.", color: "text-stone-300" },
  { tier: "Research Mode", multiplier: "0.15x", description: "Agents gather market data, competitor insights, and lead intelligence for you.", color: "text-stone-300" },
  { tier: "DIY Mode", multiplier: "0x", description: "You handle everything manually; agents are on standby.", color: "text-neutral-400" },
]

// Animated counter component
function AnimatedCounter({ target, suffix = "" }: { target: string; suffix?: string }) {
  const [count, setCount] = useState(0)
  const ref = useRef<HTMLSpanElement>(null)
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true)
        }
      },
      { threshold: 0.5 },
    )

    if (ref.current) {
      observer.observe(ref.current)
    }

    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!isVisible) return

    const numericTarget = Number.parseInt(target.replace(/\D/g, "")) || 0
    const duration = 2000
    const steps = 60
    const increment = numericTarget / steps

    let current = 0
    const timer = setInterval(() => {
      current += increment
      if (current >= numericTarget) {
        setCount(numericTarget)
        clearInterval(timer)
      } else {
        setCount(Math.floor(current))
      }
    }, duration / steps)

    return () => clearInterval(timer)
  }, [isVisible, target])

  const displayValue = target.includes("x")
    ? `${count}x`
    : target.includes("%")
      ? `${count}%`
      : target.includes("s")
        ? `${count}s`
        : target

  return (
    <span ref={ref} className="tabular-nums">
      {isVisible ? displayValue : target}
    </span>
  )
}

// Floating animation wrapper
function FloatingElement({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  return (
    <div
      className="animate-float"
      style={{
        animationDelay: `${delay}s`,
        animationDuration: "6s",
      }}
    >
      {children}
    </div>
  )
}

export default function EcosystemLandingPage() {
  const [activeTab, setActiveTab] = useState<"sdrs" | "founders">("sdrs")
  const [hoveredIntegration, setHoveredIntegration] = useState<string | null>(null)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)

  const navItems = [
    {
      name: "Central Agent",
      link: "/chat",
      icon: <Sparkles className="w-3.5 h-3.5" />,
      highlight: true,
    },
    { name: "How it Works", link: "#how-it-works" },
    { name: "For SDRs", link: "#for-sdrs" },
    { name: "For Founders", link: "#for-founders" },
    { name: "Integrations", link: "#integrations" },
  ]

  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      {/* Subtle grid background */}
      <div className="fixed inset-0 grid-background opacity-50 pointer-events-none" />
      <div className="fixed inset-0 radial-glow pointer-events-none" />

      {/* Navigation */}
      <Navbar>
        {/* Desktop Navigation */}
        <NavBody>
          <Link href="/" className="relative z-20 mr-4 flex items-center space-x-2.5 px-2 py-1">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center">
              <Image src="/logo.jpg" alt="AssembleOne" width={36} height={36} className="w-full h-full object-contain rounded-md" />
            </div>
            <span className="text-lg font-black tracking-tight text-foreground">AssembleOne</span>
          </Link>
          <NavItems items={navItems} />
          <div className="flex items-center gap-3">
            <NavbarButton href="/dashboard" variant="primary">Preview</NavbarButton>
          </div>
        </NavBody>

        {/* Mobile Navigation */}
        <MobileNav>
          <MobileNavHeader>
            <Link href="/" className="flex items-center space-x-2.5">
              <div className="w-9 h-9 rounded-xl flex items-center justify-center">
                <Image src="/logo.jpg" alt="AssembleOne" width={36} height={36} className="w-full h-full object-contain rounded-md" />
              </div>
              <span className="text-lg font-black tracking-tight text-foreground">AssembleOne</span>
            </Link>
            <MobileNavToggle
              isOpen={isMobileMenuOpen}
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            />
          </MobileNavHeader>

          <MobileNavMenu
            isOpen={isMobileMenuOpen}
            onClose={() => setIsMobileMenuOpen(false)}
          >
            {navItems.map((item, idx) => (
              <a
                key={`mobile-link-${idx}`}
                href={item.link}
                onClick={() => setIsMobileMenuOpen(false)}
                className={`relative text-sm ${item.highlight
                  ? "text-zinc-300 font-semibold flex items-center gap-1.5"
                  : "text-muted-foreground hover:text-foreground"
                  }`}
              >
                {item.icon}
                <span className="block">{item.name}</span>
              </a>
            ))}
            <div className="flex w-full flex-col gap-3 pt-4">
              <Button className="w-full bg-white text-black hover:bg-white/90" asChild>
                <Link href="/dashboard" onClick={() => setIsMobileMenuOpen(false)}>Preview</Link>
              </Button>
            </div>
          </MobileNavMenu>
        </MobileNav>
      </Navbar>

      {/* Main Hero Component */}
      <HeroSection />

      {/* YC Requests for Startups Section */}
      <YCRfsSection />

      {/* Legacy Features Section */}
      <FeaturesSection />

      {/* Logos Marquee */}
      <section id="integrations" className="py-12 border-y border-border/40 overflow-hidden">
        <div className="mb-6 text-center">
          <p className="text-sm text-muted-foreground uppercase tracking-widest">
            Connects to every tool your company needs to run
          </p>
        </div>
        <div className="flex items-center gap-8 animate-marquee">
          {[...INTEGRATIONS, ...INTEGRATIONS].map((integration, i) => (
            <div
              key={`${integration.name}-${i}`}
              className="flex items-center gap-3 px-6 py-3 rounded-xl border border-border/40 bg-card/30 backdrop-blur-sm shrink-0 hover:border-border/80 hover:bg-card/50 transition-all duration-300 group"
              onMouseEnter={() => setHoveredIntegration(integration.name)}
              onMouseLeave={() => setHoveredIntegration(null)}
            >
              <div className="opacity-70 group-hover:opacity-100 group-hover:scale-110 transition-all duration-300">
                <integration.icon className="w-8 h-8 text-white" />
              </div>
              <span className="text-sm font-semibold whitespace-nowrap">{integration.name}</span>
            </div>
          ))}
        </div>
      </section >

      {/* How It Works */}
      <section id="how-it-works" className="py-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">How AssembleOne Works</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              A complete operating system that builds, launches, and scales your company — all from a single goal prompt
            </p>
          </div>

          {/* The Algorithm */}
          <div className="mb-20">
            <div className="max-w-4xl mx-auto p-8 rounded-3xl border border-border/60 bg-card/50 backdrop-blur-sm">
              <div className="text-center mb-8">
                <h3 className="text-2xl font-black mb-2">The Founder OS Engine</h3>
                <p className="text-muted-foreground">Your goal, broken down and executed by autonomous agents</p>
              </div>

              <div className="bg-black/50 rounded-2xl p-6 mb-8 border border-border/40">
                <code className="text-2xl md:text-3xl font-mono text-center block">
                  <span className="text-zinc-300">GOAL</span>
                  <span className="text-muted-foreground"> → </span>
                  <span className="text-zinc-300">BUILD</span>
                  <span className="text-muted-foreground"> → </span>
                  <span className="text-stone-300">LAUNCH</span>
                  <span className="text-muted-foreground"> → </span>
                  <span className="text-zinc-300">SELL</span>
                  <span className="text-muted-foreground"> → </span>
                  <span className="text-zinc-300">SCALE</span>
                </code>
              </div>

              <div className="grid md:grid-cols-3 gap-6">
                <div className="p-4 rounded-xl bg-black/30 border border-white/30">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-8 h-8 rounded-lg bg-white/20 flex items-center justify-center">
                      <ShieldCheck className="w-4 h-4 text-zinc-300" />
                    </div>
                    <span className="font-black text-zinc-300">BUILD</span>
                  </div>
                  <div className="text-sm font-semibold mb-1">Product Creation</div>
                  <div className="text-xs text-muted-foreground">
                    AI agents vibe-code your product, set up infrastructure, and deploy it — no technical skills needed from you.
                  </div>
                </div>
                <div className="p-4 rounded-xl bg-black/30 border border-white/30">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-8 h-8 rounded-lg bg-white/20 flex items-center justify-center">
                      <Users className="w-4 h-4 text-stone-300" />
                    </div>
                    <span className="font-black text-stone-300">LAUNCH</span>
                  </div>
                  <div className="text-sm font-semibold mb-1">Go-to-Market</div>
                  <div className="text-xs text-muted-foreground">
                    Agents write your positioning, set up your landing page copy, and execute your go-to-market the moment your product is ready.
                  </div>
                </div>
                <div className="p-4 rounded-xl bg-black/30 border border-white/30">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-8 h-8 rounded-lg bg-white/20 flex items-center justify-center">
                      <TrendingUp className="w-4 h-4 text-zinc-300" />
                    </div>
                    <span className="font-black text-zinc-300">SELL</span>
                  </div>
                  <div className="text-sm font-semibold mb-1">Revenue Generation</div>
                  <div className="text-xs text-muted-foreground">
                    Outbound agents prospect leads, write personalized sequences, and book meetings — continuously, without a sales hire.
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Automation Tiers */}
          <div className="mb-20">
            <h3 className="text-2xl font-black text-center mb-8">Choose How Much You Stay in Control</h3>
            <div className="max-w-4xl mx-auto space-y-3">
              {AUTOMATION_TIERS.map((tier, i) => (
                <div
                  key={tier.tier}
                  className="flex items-center gap-4 p-4 rounded-xl border border-border/40 bg-card/30 hover:bg-card/50 transition-colors"
                  style={{ animationDelay: `${i * 0.1}s` }}
                >
                  <div className={`w-16 text-right font-mono font-black ${tier.color}`}>{tier.multiplier}</div>
                  <div className="flex-1">
                    <div className="font-semibold">{tier.tier}</div>
                    <div className="text-sm text-muted-foreground">{tier.description}</div>
                  </div>
                  <div
                    className="h-2 rounded-full bg-gradient-to-r from-current to-transparent"
                    style={{
                      width: `${Number.parseFloat(tier.multiplier) * 100}%`,
                      maxWidth: "120px",
                      color: tier.color.replace("text-", "").includes("emerald")
                        ? "#34d399"
                        : tier.color.includes("blue")
                          ? "#60a5fa"
                          : tier.color.includes("amber")
                            ? "#fbbf24"
                            : tier.color.includes("orange")
                              ? "#fb923c"
                              : "#f87171",
                    }}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Two Portals Section */}
      <section className="py-24 px-6 border-t border-border/40">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">One Platform, Every Function of Your Company</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Whether you're a non-tech founder with an idea or a developer ready to scale, AssembleOne runs your entire operation
            </p>
          </div>

          {/* Tab Switcher */}
          <div className="flex justify-center mb-12">
            <div className="inline-flex p-1.5 rounded-2xl border border-border/60 bg-card/50 backdrop-blur-sm">
              <button
                onClick={() => setActiveTab("sdrs")}
                className={`px-8 py-3 rounded-xl text-sm font-semibold transition-all duration-300 ${activeTab === "sdrs" ? "bg-white text-black" : "text-muted-foreground hover:text-foreground"
                  }`}
              >
                <Users className="w-4 h-4 inline mr-2" />
                For Solo Founders
              </button>
              <button
                onClick={() => setActiveTab("founders")}
                className={`px-8 py-3 rounded-xl text-sm font-semibold transition-all duration-300 ${activeTab === "founders" ? "bg-white text-black" : "text-muted-foreground hover:text-foreground"
                  }`}
              >
                <GraduationCap className="w-4 h-4 inline mr-2" />
                For Non-Tech Builders
              </button>
            </div>
          </div>

          {/* SDRs Content */}
          {activeTab === "sdrs" && (
            <div id="for-sdrs" className="animate-fade-in">
              <div className="grid lg:grid-cols-2 gap-12 items-center mb-16">
                <div>
                  <h3 className="text-3xl font-black mb-6">Stop Managing. Start Building.</h3>
                  <p className="text-lg text-muted-foreground mb-8 leading-relaxed">
                    Traditional startups require a full team — engineers, PMs, marketers, salespeople. AssembleOne gives you autonomous agents that code your product, validate product-market fit, run your marketing, and close your first customers — before you hire anyone.
                  </p>
                  <div className="space-y-4 mb-8">
                    {[
                      "Describe your idea in plain language — agents create your product spec and start coding",
                      "Agents autonomously deploy your app, set up your domain, and write your landing page",
                      "AI monitors traffic, user behavior, and revenue in real time",
                      "Outbound agents find your ideal customers and run personalized email sequences",
                      "Marketing agents run and optimize paid campaigns across channels automatically",
                    ].map((item, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <div className="w-6 h-6 rounded-full bg-white/20 flex items-center justify-center shrink-0 mt-0.5">
                          <Check className="w-3.5 h-3.5 text-zinc-300" />
                        </div>
                        <span className="text-muted-foreground">{item}</span>
                      </div>
                    ))}
                  </div>
                  <Button size="lg" className="bg-white text-black hover:bg-white/90" asChild>
                    <Link href="/dashboard">
                      Open Command Center
                      <ArrowRight className="w-5 h-5 ml-2" />
                    </Link>
                  </Button>
                </div>

                {/* Agent Feature Cards */}
                <div className="grid grid-cols-2 gap-4">
                  {[
                    { icon: Target, title: "Idea → Code", desc: "Prompt to deployed product" },
                    { icon: Eye, title: "Auto Deploy", desc: "Live on the web in hours" },
                    { icon: Brain, title: "Market Radar", desc: "Live buyer intent signals" },
                    { icon: FileCheck, title: "Outbound Agent", desc: "Autonomous email sequences" },
                    { icon: BarChart3, title: "Growth Engine", desc: "Traffic + revenue monitoring" },
                    { icon: Lock, title: "Founder Mode", desc: "You approve before agents act" },
                  ].map((feature, i) => (
                    <div
                      key={feature.title}
                      className="p-5 rounded-2xl border border-border/40 bg-card/30 hover:bg-card/50 hover:border-border/80 transition-all duration-300"
                    >
                      <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center mb-3">
                        <feature.icon className="w-5 h-5" />
                      </div>
                      <div className="font-semibold mb-1">{feature.title}</div>
                      <div className="text-xs text-muted-foreground">{feature.desc}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Founders Content */}
          {activeTab === "founders" && (
            <div id="for-founders" className="animate-fade-in">
              <div className="grid lg:grid-cols-2 gap-12 items-center mb-16">
                <div>
                  <h3 className="text-3xl font-black mb-6">Scale Revenue, Not Headcount</h3>
                  <p className="text-lg text-muted-foreground mb-8 leading-relaxed">
                    Stop burning cash on massive SDR teams. FORGE provides an elite, always-on AI Growth Team that validates ideas, builds pipelines, and drives growth.
                  </p>
                  <div className="space-y-4 mb-8">
                    {[
                      "Deploy specialized agents (Research, Outreach, Analytics)",
                      "Monitor real-time pipeline velocity and MRR impact",
                      "Get predictive churn warnings and intervention strategies",
                      "Auto-generate 30-day Go-To-Market playbooks",
                      "Maintain complete control with final-review dashboards",
                    ].map((item, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <div className="w-6 h-6 rounded-full bg-white/20 flex items-center justify-center shrink-0 mt-0.5">
                          <Check className="w-3.5 h-3.5 text-zinc-300" />
                        </div>
                        <span className="text-muted-foreground">{item}</span>
                      </div>
                    ))}
                  </div>
                  <Button size="lg" className="bg-white text-black hover:bg-white/90" asChild>
                    <Link
                      href="/pm/dashboard"
                    >
                      View Executive Dashboard
                      <ArrowUpRight className="w-5 h-5 ml-2" />
                    </Link>
                  </Button>
                </div>

                {/* Intelligence Modules */}
                <div className="space-y-3">
                  <div className="text-sm font-semibold text-muted-foreground mb-4">INTELLIGENCE MODULES</div>
                  {INTELLIGENCE_MODULES.map((module, i) => (
                    <div
                      key={module.name}
                      className="flex items-center gap-4 p-4 rounded-xl border border-border/40 bg-card/30 hover:bg-card/50 hover:border-border/80 transition-all duration-300"
                    >
                      <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
                        <module.icon className="w-6 h-6 text-zinc-300" />
                      </div>
                      <div>
                        <div className="font-semibold">{module.name}</div>
                        <div className="text-sm text-muted-foreground">{module.description}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* What Founders Get */}
              <div className="grid md:grid-cols-3 gap-6">
                {[
                  {
                    icon: Award,
                    title: "PMF Certainty",
                    desc: "Data-backed confidence scores before you spend engineering time on new features.",
                  },
                  {
                    icon: TrendingUp,
                    title: "Predictable Revenue",
                    desc: "AI forecasts ARR and flags accounts at risk of churn before they leave.",
                  },
                  {
                    icon: MessageSquare,
                    title: "Complete Visibility",
                    desc: "The Central Dashboard gives you a god-view of your entire growth operation.",
                  },
                ].map((item) => (
                  <div
                    key={item.title}
                    className="p-6 rounded-2xl border border-border/40 bg-card/30 hover:bg-card/50 transition-colors"
                  >
                    <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center mb-4">
                      <item.icon className="w-6 h-6 text-zinc-300" />
                    </div>
                    <div className="text-lg font-semibold mb-2">{item.title}</div>
                    <div className="text-sm text-muted-foreground leading-relaxed">{item.desc}</div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Deep Work Metrics */}
      <section className="py-24 px-6 border-t border-border/40 relative overflow-hidden">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">One Platform, Every Function of Your Company</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Whether you're a non-tech founder with an idea or a developer ready to scale, AssembleOne runs your entire operation
            </p>
          </div>
        </div>
      </section>

      {/* Integrations Grid */}
      <section className="py-24 px-6 bg-[#0a0a0a] border-y border-border/40 relative overflow-hidden">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">AssembleOne vs Building a Startup Team</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Most founders need 5+ hires to run a company. AssembleOne replaces every function with an autonomous agent.
            </p>
          </div>

          <div className="rounded-3xl border border-border/60 bg-card/50 backdrop-blur-sm overflow-hidden">
            {/* Header */}
            <div className="grid grid-cols-3 border-b border-border/40">
              <div className="p-6 font-semibold">Capability</div>
              <div className="p-6 text-center font-black text-zinc-300 border-x border-border/40 bg-white/5">
                AssembleOne Agents
              </div>
              <div className="p-6 text-center font-semibold text-muted-foreground">Traditional Startup Team</div>
            </div>

            {/* Rows */}
            {FORGE_VS_CRM.map((row, i) => (
              <div
                key={row.feature}
                className={`grid grid-cols-3 ${i < FORGE_VS_CRM.length - 1 ? "border-b border-border/40" : ""}`}
              >
                <div className="p-4 text-sm">{row.feature}</div>
                <div className="p-4 flex justify-center items-center border-x border-border/40 bg-white/5">
                  {row.forge === true ? (
                    <CheckCircle2 className="w-5 h-5 text-zinc-300" />
                  ) : row.forge === false ? (
                    <XCircle className="w-5 h-5 text-neutral-400" />
                  ) : (
                    <Minus className="w-5 h-5 text-stone-300" />
                  )}
                </div>
                <div className="p-4 flex justify-center items-center">
                  {row.ats === true ? (
                    <CheckCircle2 className="w-5 h-5 text-zinc-300" />
                  ) : row.ats === false ? (
                    <XCircle className="w-5 h-5 text-muted-foreground" />
                  ) : (
                    <Minus className="w-5 h-5 text-stone-300" />
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section >

      {/* Integrations */}
      < section id="integrations" className="py-24 px-6 border-t border-border/40" >
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">Connects to Every Tool Your Business Runs On</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              AssembleOne connects to the tools your company already uses. Pull data from anywhere, deploy to any platform, and let agents operate your full stack automatically.
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
            {INTEGRATIONS.map((integration) => (
              <div
                key={integration.name}
                className="group p-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md hover:bg-white/10 hover:border-white/20 transition-all duration-300 flex flex-col items-center gap-3"
                onMouseEnter={() => setHoveredIntegration(integration.name)}
                onMouseLeave={() => setHoveredIntegration(null)}
              >
                <div className="w-12 h-12 flex items-center justify-center rounded-lg group-hover:scale-110 transition-transform duration-300 opacity-70 group-hover:opacity-100">
                  <integration.icon className="w-8 h-8 text-white" />
                </div>
                <span className="text-sm font-semibold">{integration.name}</span>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <p className="text-muted-foreground mb-4">Don't see your stack? We're connecting new platforms every week.</p>
            <Button variant="outline" size="lg" className="border-white/10 hover:bg-white/10 hover:text-white">
              Request Integration
              <ChevronRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        </div>
      </section >

      {/* Social Proof / Testimonials */}
      <section className="py-24 px-6 border-t border-border/40">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4">Why Solo Founders Choose AssembleOne</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                quote: "I went from having an idea to a live product with paying users in under two weeks. I never wrote a single line of code or sent a single cold email myself.",
                author: "Aryan M.",
                role: "Solo Founder, SaaS Product",
              },
              {
                quote: "AssembleOne replaced what would have been a $30k/month team. The agents built my landing page, found my first 50 leads, and booked 8 discovery calls — all while I was sleeping.",
                author: "Priya K.",
                role: "Indie Hacker & Founder",
              },
              {
                quote: "I'm not technical at all. I described what I wanted to build and the agents handled the entire product, marketing site, and outreach. It's like having a co-founder who never sleeps.",
                author: "James T.",
                role: "Non-Tech Founder",
              },
            ].map((testimonial, i) => (
              <div key={i} className="p-6 rounded-2xl border border-border/40 bg-card/30">
                <div className="flex gap-1 mb-4">
                  {[...Array(5)].map((_, j) => (
                    <Star key={j} className="w-4 h-4 fill-amber-400 text-stone-300" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-6 leading-relaxed">"{testimonial.quote}"</p>
                <div>
                  <div className="font-semibold">{testimonial.author}</div>
                  <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 px-6 border-t border-border/40">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-black mb-6">Ready to Launch Your Company on Autopilot?</h2>
          <p className="text-xl text-muted-foreground mb-12 max-w-2xl mx-auto">
            Join the next wave of solo founders building real companies with zero team. Describe your idea and let agents do the rest — from code to customers.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button size="lg" className="h-16 px-10 text-lg bg-white text-black hover:bg-white/90 group" asChild>
              <Link href="#waitlist">
                <MessageSquare className="w-5 h-5 mr-2" />
                Request Early Access
                <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-border/40">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <div className="w-6 h-6 flex items-center justify-center">
              <Image src="/logo.jpg" alt="AssembleOne" width={24} height={24} className="w-full h-full object-contain rounded-sm" />
            </div>
            <span className="font-black">AssembleOne</span>
            <span className="text-muted-foreground text-sm">Agentic Founder OS</span>
          </div>
          <div className="flex items-center gap-8 text-sm text-muted-foreground">
            <a href="#" className="hover:text-foreground transition-colors">
              Privacy
            </a>
            <a href="#" className="hover:text-foreground transition-colors">
              Terms
            </a>
            <a href="#" className="hover:text-foreground transition-colors">
              Contact
            </a>
          </div>
        </div>
      </footer >
    </div >
  )
}
